[build]
builder = "dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Backend service configuration
[[services]]
name = "backend"
source = "."
dockerfile = "Dockerfile"

[services.variables]
RAILWAY_ENVIRONMENT = "$RAILWAY_ENVIRONMENT"
RAILWAY_PROJECT_ID = "$RAILWAY_PROJECT_ID"
DATABASE_URL = "$DATABASE_URL"
POSTGRES_URL = "$DATABASE_URL"
MONGODB_URL = "$MONGODB_URL"

# Frontend service configuration  
[[services]]
name = "frontend"
source = "web"
dockerfile = "web/Dockerfile"

[services.variables]
NEXT_PUBLIC_API_URL = "https://${{RAILWAY_PUBLIC_DOMAIN}}/api"
PORT = "$PORT"
PUBLIC_URL = "https://${{RAILWAY_PUBLIC_DOMAIN}}"
NEXT_PUBLIC_BRAND_NAME = "Bulldozer"
NEXT_PUBLIC_LOGO_URL = "/logo.png"
NEXT_PUBLIC_BRAND_COLOR = "#ff6b35"