[build]
builder = "dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# PostgreSQL Database service
[[services]]
name = "Bulldozer-PostgreSQL"
source = "postgres:15"

# Backend service configuration
[[services]]
name = "Bulldozer-Backend"
source = "."
dockerfile = "Dockerfile"

[services.variables]
RAILWAY_ENVIRONMENT = "$RAILWAY_ENVIRONMENT"
RAILWAY_PROJECT_ID = "$RAILWAY_PROJECT_ID"
DATABASE_URL = "$DATABASE_URL"
POSTGRES_URL = "$DATABASE_URL"
MONGODB_URL = "$MONGODB_URL"
PORT = "8000"

# Frontend service configuration  
[[services]]
name = "Bulldozer-Frontend"
source = "web"
dockerfile = "web/Dockerfile"

[services.variables]
NEXT_PUBLIC_API_URL = "https://bulldozerai.up.railway.app/api"
PORT = "8080"
PUBLIC_URL = "https://bulldozer825.com"
NEXT_PUBLIC_BRAND_NAME = "Bulldozer"
NEXT_PUBLIC_LOGO_URL = "/logo.png"
NEXT_PUBLIC_BRAND_COLOR = "#ff6b35"